import { createHash, randomUUID } from "node:crypto";
import { writeFile, unlink } from "node:fs/promises";
import { GatewayError } from "./errors.js";
import { linkedPage } from "./links.js";
const bytes=t=>Buffer.byteLength(t,"utf8");
const docOf=r=>r?.data?.document??r?.data??r?.document??r;
function revision(doc){const id=doc?.revision_id;if(id===undefined||id===null)throw new GatewayError("REVISION_MISSING","Feishu did not return a revision_id");return String(id);}
export class GatewayService {
  constructor(cli,guard,receipts,config){Object.assign(this,{cli,guard,receipts,config});}
  async identityStatus(){const raw=await this.cli.authStatus(),d=raw?.data??raw;return {ok:true,authenticated:Boolean(d?.authenticated??d?.logged_in??d?.verified??raw?.ok),identity:raw?.identity??"user",root_aliases:Object.keys(this.guard.roots()),public_base_url:this.config.publicBaseUrl||null};}
  async listAllowedRoots(){const roots=[];for(const [alias,token] of Object.entries(this.guard.roots())){const page=await this.guard.resolveAllowed(token);roots.push({alias,title:page.title,node_token:page.node_token,obj_type:page.obj_type});}return {ok:true,roots};}
  async getProjectTree({max_depth,root_alias="awiki"}){const t=await this.guard.tree(max_depth,root_alias);return {ok:true,root_alias:t.alias,root:linkedPage(t.root,this.config),nodes:t.nodes.map(n=>linkedPage(n,this.config)),truncated:t.truncated};}
  async readPage({page_ref,detail}){const page=linkedPage(await this.guard.resolveAllowed(page_ref),this.config),doc=docOf(await this.cli.docFetch(page.obj_token,detail));return {ok:true,page,revision:revision(doc),markdown:doc.content??"",tips:doc.tips??""};}
  async createChildPage(input){return this.write("create_child_page",input.operation_id,input,async()=>{const parent=await this.guard.resolveAllowed(input.parent_ref||this.guard.rootToken(input.root_alias??"awiki"));const raw=await this.cli.nodeCreate(parent.node_token,input.title),created=raw?.data??raw;const ref=created.node_token??created?.node?.node_token;if(!ref)throw new GatewayError("CREATE_RESPONSE_INVALID","Feishu did not return the new node token");const page=await this.guard.resolveAllowed(ref);return {ok:true,page};});}
  async createJournalEntry(input){if(bytes(input.markdown)>this.config.maxMarkdownBytes)throw new GatewayError("CONTENT_TOO_LARGE","Markdown exceeds the configured byte limit");return this.write("create_journal_entry",input.operation_id,input,async()=>{const parent=await this.guard.resolveAllowed(this.guard.rootToken("journal"));const raw=await this.cli.nodeCreate(parent.node_token,input.title),created=raw?.data??raw,ref=created.node_token??created?.node?.node_token;if(!ref)throw new GatewayError("CREATE_RESPONSE_INVALID","Feishu did not return the new node token");const page=await this.guard.resolveAllowed(ref),current=docOf(await this.cli.docFetch(page.obj_token,"full")),rev=revision(current);await this.cli.docUpdate(page.obj_token,"append",input.markdown,rev);const after=docOf(await this.cli.docFetch(page.obj_token,"simple"));return {ok:true,page,revision:revision(after)};});}
  async appendMarkdown(i){return this.updateMarkdown("append_markdown","append",i);} async replacePage(i){return this.updateMarkdown("replace_page","overwrite",i);}
  async updateMarkdown(tool,command,input){if(bytes(input.markdown)>this.config.maxMarkdownBytes)throw new GatewayError("CONTENT_TOO_LARGE","Markdown exceeds the configured byte limit");return this.write(tool,input.operation_id,input,async()=>{const page=await this.guard.resolveAllowed(input.page_ref),current=docOf(await this.cli.docFetch(page.obj_token,"full")),rev=revision(current);if(String(input.expected_revision)!==rev)throw new GatewayError("REVISION_CONFLICT","The page changed after it was read; read it again before writing",{expected:String(input.expected_revision),current:rev});const raw=await this.cli.docUpdate(page.obj_token,command,input.markdown,rev),after=docOf(await this.cli.docFetch(page.obj_token,"simple"));return {ok:true,page,previous_revision:rev,revision:revision(after),update:raw?.data??raw};});}
  async uploadPageImage(input){const safeInput={...input,data_base64:createHash("sha256").update(input.data_base64).digest("hex")};return this.write("upload_page_image",input.operation_id,safeInput,async()=>{const page=await this.guard.resolveAllowed(input.page_ref),current=docOf(await this.cli.docFetch(page.obj_token,"full")),rev=revision(current);if(String(input.expected_revision)!==rev)throw new GatewayError("REVISION_CONFLICT","The page changed after it was read; read it again before writing",{expected:String(input.expected_revision),current:rev});const payload=Buffer.from(input.data_base64,"base64");if(!payload.length||payload.length>this.config.maxImageBytes)throw new GatewayError("IMAGE_SIZE_INVALID","Image is empty or exceeds the configured byte limit");const ext={"image/png":".png","image/jpeg":".jpg","image/gif":".gif","image/webp":".webp","image/bmp":".bmp"}[input.mime_type];if(!ext)throw new GatewayError("IMAGE_TYPE_INVALID","Unsupported image MIME type");const name=`${randomUUID()}${ext}`,absolute=`${this.config.larkWorkDir}/${name}`;await writeFile(absolute,payload,{mode:0o600,flag:"wx"});try{const raw=await this.cli.mediaInsert(page.obj_token,`./${name}`,input.caption),after=docOf(await this.cli.docFetch(page.obj_token,"simple"));return {ok:true,page,previous_revision:rev,revision:revision(after),media:raw?.data??raw};}finally{await unlink(absolute).catch(()=>{});}});}
  async getSyncReceipt({operation_id}){const r=this.receipts.get(operation_id);if(!r)throw new GatewayError("RECEIPT_NOT_FOUND","No receipt exists for operation_id");return {ok:true,receipt:{operation_id:r.operation_id,tool_name:r.tool_name,status:r.status,result:r.result,error:r.error,created_at:r.created_at,updated_at:r.updated_at}};}
  withLinks(result){return result?.page?{...result,page:linkedPage(result.page,this.config)}:result;}
  async write(tool,id,input,action){const s=this.receipts.begin(id,tool,input);if(s.replay)return {...this.withLinks(s.result),idempotent_replay:true};try{const result=this.withLinks(await action());this.receipts.succeed(id,result);return result;}catch(error){this.receipts.fail(id,error);throw error;}}
}
