import express from "express";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import { z } from "zod";
import { safeError } from "./errors.js";
const operationId=z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/),pageRef=z.string().min(8).max(500),expectedRevision=z.union([z.string().min(1).max(64),z.number().int().nonnegative()]);
function output(value){return {content:[{type:"text",text:JSON.stringify(value)}],structuredContent:value,isError:value?.ok===false};}
const linkHelp=" Document results may add page.feishu_url and page.awiki_local_url (tree nodes carry the same fields). awiki_local_url is only for the user’s browser on the Mac running the viewer, not a remote reading API for cloud agents. Phones/other computers must use feishu_url. The local URL grants no additional document permissions; native embedding may require separate web login/configuration.";
function register(server,name,description,schema,handler){server.registerTool(name,{description:description+linkHelp,inputSchema:schema},async args=>{try{return output(await handler(args));}catch(error){return output(safeError(error));}});}
export function makeMcpServer(service){
  const rootAlias=z.enum(["awiki","journal"]),s=new McpServer({name:"awiki-feishu-private-gateway",version:"0.2.0"});
  if(service.control){
    const contextId=z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$/);
    register(s,'register_context','Register/update a minimal self-reported conversation summary in the local control area. User must request registration. Do not invent native session IDs, infer authorship from document titles, store credentials/full transcripts, dispatch agents, or modify documents. context_id is only a registry key; native_session_id is separate. Missing native ID/link must be null. Report real source/evidence in identity_basis. Use expected_revision=0 for new records.',{
      context_id:contextId,expected_revision:z.number().int().min(0),provider:z.enum(['codex','chatgpt','other','unknown']),native_session_id:z.string().max(200).nullable(),session_url:z.string().max(600).nullable(),title:z.string().min(1).max(200),agent_label:z.string().min(1).max(200),identity_basis:z.string().min(1).max(600),summary:z.string().max(2000),goal:z.string().max(1200),decisions:z.string().max(2000),open_questions:z.string().max(2000),next_step:z.string().max(1200),document_refs:z.array(z.string().regex(/^[A-Za-z0-9_-]{8,200}$/)).max(20),
      conversation_timing:z.object({started_at:z.string().datetime().nullable(),last_turn_started_at:z.string().datetime().nullable(),last_turn_completed_at:z.string().datetime().nullable(),last_turn_id:z.string().max(200),excluded_collection_turn_ids:z.array(z.string().max(200)).max(100),source:z.string().min(1).max(600)}).optional().describe('Verified platform timestamps in UTC. Last turn excludes self-description/collection requests and replies; never substitute registry updated_at. Omit when unknown; omission preserves existing timing.')
    },x=>service.control.register(x));
    register(s,'read_context','Read a registered conversation summary, not full chat history. Its ID is a locator, not permission to send messages or execute tasks.',{context_id:contextId},x=>service.control.read(x));
    register(s,'list_contexts','List minimal registered context summaries associated only with currently allowed documents. No live task state or automatic conversation discovery.',{},()=>service.control.list());
  }
  register(s,"identity_status","Check safe Feishu identity state and configured root aliases. Returns no credentials.",{},()=>service.identityStatus());
  register(s,"list_allowed_roots","List only the named Wiki roots configured in the gateway allowlist.",{},()=>service.listAllowedRoots());
  register(s,"get_project_tree","List one configured root page and its descendants.",{root_alias:rootAlias.default("awiki"),max_depth:z.number().int().min(1).max(20).optional()},x=>service.getProjectTree(x));
  register(s,"create_child_page","Create a docx child under an allowed root or descendant. Requires a stable operation_id.",{root_alias:rootAlias.default("awiki"),parent_ref:pageRef.optional(),title:z.string().trim().min(1).max(200),operation_id:operationId},x=>service.createChildPage(x));
  register(s,"create_journal_entry","Create and populate one new docx page directly under the journal root. Requires a stable operation_id.",{title:z.string().trim().min(1).max(200),markdown:z.string().min(1),operation_id:operationId},x=>service.createJournalEntry(x));
  register(s,"read_page","Read a docx page only inside the configured AWiki tree; returns revision for guarded writes.",{page_ref:pageRef,detail:z.enum(["simple","full"]).default("simple")},x=>service.readPage(x));
  register(s,"append_markdown","Append Markdown after a read. Fails on revision conflict and never forces an overwrite.",{page_ref:pageRef,markdown:z.string().min(1),expected_revision:expectedRevision,operation_id:operationId},x=>service.appendMarkdown(x));
  register(s,"replace_page","Replace a page body after a read. Fails on revision conflict; rich blocks may be lost.",{page_ref:pageRef,markdown:z.string(),expected_revision:expectedRevision,operation_id:operationId},x=>service.replacePage(x));
  register(s,"upload_page_image","Append one base64 image to an allowed page after a revision check.",{page_ref:pageRef,data_base64:z.string().min(4),mime_type:z.enum(["image/png","image/jpeg","image/gif","image/webp","image/bmp"]),caption:z.string().max(500).optional(),expected_revision:expectedRevision,operation_id:operationId},x=>service.uploadPageImage(x));
  register(s,"get_sync_receipt","Read the idempotency receipt for a write operation_id.",{operation_id:operationId},x=>service.getSyncReceipt(x));return s;
}
export function makeApp(service){const app=express();app.disable("x-powered-by");app.use(express.json({limit:"16mb"}));app.get("/healthz",(_q,r)=>r.json({ok:true}));app.post("/mcp",async(req,res)=>{const server=makeMcpServer(service),transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});res.on("close",()=>{transport.close();server.close();});try{await server.connect(transport);await transport.handleRequest(req,res,req.body);}catch{if(!res.headersSent)res.status(500).json({ok:false,error:{code:"MCP_TRANSPORT_ERROR",message:"MCP request failed"}});}});app.get("/mcp",(_q,r)=>r.status(405).set("Allow","POST").end());app.delete("/mcp",(_q,r)=>r.status(405).set("Allow","POST").end());return app;}
